insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (1,1,3,'2020-11-02','it was good',2);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (1,2,4,'2020-11-02','it was a very creative solution',2);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (1,3,5,'2020-11-02','it is perfect',2);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (1,4,5,'2020-11-03','proved your knowledge',2);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (1,5,4,'2020-11-03','no more questions',2);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (1,6,5,'2020-11-05','who knows knows',2);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (1,7,4,'2020-11-05','it was good',2);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (1,8,5,'2020-11-06','you have proved your knowledge',2);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (1,9,4,'2020-11-06','it was a very creative and perfect solution',2);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (1,10,5,'2020-11-07','I couldnt have done that better either',2);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (1,11,3,'2020-11-08','it will get better',2);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (1,12,2,'2020-11-09','it almost failed',2);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (1,13,1,'2020-11-10','unfortunately this failed',2);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (1,14,5,'2020-11-10','it was good',2);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (1,15,1,'2020-11-11','try again :(',2);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (1,16,3,'2020-11-12','keep it up',2);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (1,17,4,'2020-11-12','never give up',2);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (1,18,5,'2020-11-12','clever solution',2);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (1,19,4,'2020-11-12','it was good',2);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (1,20,3,'2020-11-12','it will get better',2);


insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (2,1,4,'2020-11-02','it was good',8);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (2,2,3,'2020-11-02','it was a very creative solution',8);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (2,3,2,'2020-11-02','it is perfect',8);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (2,4,1,'2020-11-03','proved your knowledge',8);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (2,5,2,'2020-11-03','no more questions',8);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (2,6,1,'2020-11-05','try again :(',8);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (2,7,1,'2020-11-05','try again :(',8);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (2,8,3,'2020-11-06','you have proved your knowledge',8);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (2,9,4,'2020-11-06','it was a very creative and perfect solution',8);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (2,10,4,'2020-11-07','I couldnt have done that better either',8);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (2,11,2,'2020-11-08','it will get better',8);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (2,12,3,'2020-11-09','it almost failed',8);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (2,13,5,'2020-11-10','unfortunately this failed',8);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (2,14,1,'2020-11-10','unfortunately this failed',8);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (2,15,2,'2020-11-11','try again :(',8);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (2,16,4,'2020-11-12','keep it up',8);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (2,17,5,'2020-11-12','never give up',8);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (2,18,3,'2020-11-12','clever solution',8);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (2,19,4,'2020-11-12','it was good',8);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (2,20,4,'2020-11-12','it will get better',8);

insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (5,1,4,'2020-11-02','it was good',3);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (5,2,1,'2020-11-02','it was a very creative solution',3);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (5,3,1,'2020-11-02','it is perfect',3);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (5,4,3,'2020-11-03','proved your knowledge',3);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (5,5,4,'2020-11-03','no more questions',3);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (5,6,2,'2020-11-05','try again :(',3);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (5,7,2,'2020-11-05','try again :(',3);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (5,8,3,'2020-11-06','you have proved your knowledge',3);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (5,9,3,'2020-11-06','it was a very creative and perfect solution',3);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (5,10,5,'2020-11-07','I couldnt have done that better either',3);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (5,11,3,'2020-11-08','it will get better',3);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (5,12,2,'2020-11-09','it almost failed',3);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (5,13,4,'2020-11-10','unfortunately this failed',3);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (5,14,1,'2020-11-10','unfortunately this failed',3);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (5,15,2,'2020-11-11','try again :(',3);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (5,16,4,'2020-11-12','keep it up',3);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (5,17,5,'2020-11-12','never give up',3);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (5,18,3,'2020-11-12','clever solution',3);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (5,19,4,'2020-11-12','it was good',3);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (5,20,4,'2020-11-12','it will get better',3);

insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (4,1,3,'2020-11-02','it was good',1);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (4,2,5,'2020-11-02','it was a very creative solution',1);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (4,3,3,'2020-11-02','it is perfect',1);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (4,4,5,'2020-11-03','proved your knowledge',1);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (4,5,2,'2020-11-03','it almost failed',1);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (4,6,1,'2020-11-05','try again :(',1);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (4,7,1,'2020-11-05','try again :(',1);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (4,8,2,'2020-11-06','it almost failed',1);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (4,9,2,'2020-11-06','never give up',1);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (4,10,5,'2020-11-07','I couldnt have done that better either',1);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (4,11,2,'2020-11-08','it will get better',1);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (4,12,4,'2020-11-09','it almost failed',1);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (4,13,5,'2020-11-10','unfortunately this failed',1);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (4,14,1,'2020-11-10','unfortunately this failed',1);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (4,15,2,'2020-11-11','try again :(',1);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (4,16,2,'2020-11-12','keep it up',1);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (4,17,3,'2020-11-12','never give up',1);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (4,18,3,'2020-11-12','clever solution',1);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (4,19,3,'2020-11-12','it was good',1);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (4,20,2,'2020-11-12','it will get better',1);


insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (11,1,4,'2020-11-02','it was good',6);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (11,2,3,'2020-11-02','it was a very creative solution',6);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (11,3,2,'2020-11-02','it is perfect',6);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (11,4,5,'2020-11-03','proved your knowledge',6);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (11,5,3,'2020-11-03','no more questions',6);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (11,6,1,'2020-11-05','try again :(',6);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (11,7,1,'2020-11-05','try again :(',6);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (11,8,3,'2020-11-06','you have proved your knowledge',6);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (11,9,4,'2020-11-06','it was a very creative and perfect solution',6);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (11,10,5,'2020-11-07','I couldnt have done that better either',6);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (11,11,2,'2020-11-08','it will get better',6);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (11,12,4,'2020-11-09','it almost failed',6);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (11,13,5,'2020-11-10','unfortunately this failed',6);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (11,14,1,'2020-11-10','unfortunately this failed',6);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (11,15,2,'2020-11-11','try again :(',6);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (11,16,4,'2020-11-12','keep it up',6);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (11,17,5,'2020-11-12','never give up',6);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (11,18,3,'2020-11-12','clever solution',6);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (11,19,4,'2020-11-12','it was good',6);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (11,20,4,'2020-11-12','it will get better',6);

insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (6,1,3,'2020-11-02','it was good',11);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (6,2,3,'2020-11-02','it was a very creative solution',11);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (6,3,4,'2020-11-02','it is perfect',11);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (6,4,5,'2020-11-03','proved your knowledge',11);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (6,5,3,'2020-11-03','no more questions',11);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (6,6,2,'2020-11-05','try again :(',11);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (6,7,2,'2020-11-05','try again :(',11);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (6,8,3,'2020-11-06','you have proved your knowledge',11);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (6,9,4,'2020-11-06','it was a very creative and perfect solution',11);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (6,10,5,'2020-11-07','I couldnt have done that better either',11);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (6,11,2,'2020-11-08','it will get better',11);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (6,12,4,'2020-11-09','it almost failed',11);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (6,13,5,'2020-11-10','unfortunately this failed',11);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (6,14,3,'2020-11-10','unfortunately this failed',11);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (6,15,2,'2020-11-11','try again :(',11);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (6,16,4,'2020-11-12','keep it up',11);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (6,17,5,'2020-11-12','never give up',11);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (6,18,3,'2020-11-12','clever solution',11);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (6,19,4,'2020-11-12','it was good',11);
insert into reviews (student_id, project_id, mark, date_of_review, review_description, reviewer_id) values (6,20,4,'2020-11-12','it will get better',11);